backend:
  name: github
  repo: song18903182386-spec/new
  branch: main
  client_id: 0v231ijb962I7FIPo9dr
  client_secret: 4b2414e9c637dbf9eb032f0260c60a4255fff9a8
media_folder: "img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "business"
    label: "干中求活"
    folder: "posts/business"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "封面图", name: "cover", widget: "image", required: false}
      - {label: "正文内容", name: "body", widget: "markdown"}
  - name: "ai"
    label: "爱学习"
    folder: "posts/ai"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "封面图", name: "cover", widget: "image", required: false}
  - name: "life"
    label: "来去如风"
    folder: "posts/life"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "封面图", name: "cover", widget: "image", required: false}
      - {label: "正文内容", name: "body", widget: "markdown"}
  - name: "family"
    label: "家里那点事"
    folder: "posts/family"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "封面图", name: "cover", widget: "image", required: false}
      - {label: "正文内容", name: "body", widget: "markdown"}
  - name: "travel"
    label: "想自驾全国"
    folder: "posts/travel"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "封面图", name: "cover", widget: "image", required: false}
      - {label: "正文内容", name: "body", widget: "markdown"}
